### ISSUE TITLE
Error: input stream: Status code: 429

### ISSUE THREAD

**Issue by Harmiox** [fent/node-ytdl-core#444]
Everything was working fine earlier today and yesterday until all of a sudden I started getting this error multiple time in my log file. I've never had a 429 response with this lib before.

`Error: input stream: Status code: 429
    at ClientRequest.httpLib.get (/root/discord/music/poco/node_modules/miniget/lib/index.js:125:19)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)`

**Comment by encloinc** [comment]
Same thing is happening to me!

**Comment by encloinc** [comment]
What seems to happen is, like you im using a vps, it stops working after like a few requests.

**Comment by fent** [comment]
this status means that too many requests are being made too quickly

https://httpstatuses.com/429

I recently updated [miniget](https://github.com/fent/node-miniget), the http library that this library uses. the reconnect logic was refactored and moved around. so at first i thought that might be the issue. but in #445, @encloinc is using ytdl-core@0.29.2, which uses the old version of miniget.

@encloinc, can you run `npm ls miniget` and see what version it prints?

could also be that youtube changed their website, adding more rate limiting.

**Comment by encloinc** [comment]
`-- ytdl-core@0.29.2
  +-- m3u8stream@0.6.2
  | `-- miniget@1.5.1  deduped
  `-- miniget@1.5.1

**Comment by encloinc** [comment]
I dont know if its a rate limiting issue though, because when I restart the vps it works again for a few requests. Its quite weird.

**Comment by fent** [comment]
if youtube is rate limiting requests more, one solution can be to

> -- ytdl-core@0.29.2
>   +-- m3u8stream@0.6.2
>   | `-- miniget@1.5.1  deduped
>   `-- miniget@1.5.1```

ok thanks. that means this issue is originating from a change from youtube, rather than the recent update.



> I dont know if its a rate limiting issue though, because when I restart the vps it works again for a few requests.

it's working again because there was some time when your vps didn't make any requests, not because it was restarted.



> And I wouldnt be like surpassing the limit too much, my vps makes no more than a request every 3 minutes

is this for a bot that's shared in a server? does it get a lot of requests?

**Comment by encloinc** [comment]
> if youtube is rate limiting requests more, one solution can be to
> 
> > -- ytdl-core@0.29.2
> > +-- m3u8stream@0.6.2
> > | `-- miniget@1.5.1  deduped `-- miniget@1.5.1```
> 
> ok thanks. that means this issue is originating from a change from youtube, rather than the recent update.
> 
> > I dont know if its a rate limiting issue though, because when I restart the vps it works again for a few requests.
> 
> it's working again because there was some time when your vps didn't make any requests, not because it was restarted.
> 
> > And I wouldnt be like surpassing the limit too much, my vps makes no more than a request every 3 minutes
> 
> is this for a bot that's shared in a server? does it get a lot of requests?

It is a youtube-mp3 converter site, and it doesnt really. Also when I restart the vps it restarts in like 5 minutes

**Comment by HcgRandon** [comment]
Same here, And I'm on an older version. Def a YouTube change. Hopefully there is a workaround

**Comment by encloinc** [comment]
Yeah.

**Comment by edunad** [comment]
Just started happening as well for me, i use this for a personal player and i'm the only user

**Comment by encloinc** [comment]
Yeah it definitley isnt related to actual rate limits I think.

**Comment by mh4ck** [comment]
Same here, we're fucked up.

**Comment by HcgRandon** [comment]
I have friends seeing some issues but much less then me, however they use Lavaplayer. Additionally they also have US servers, mine are EU, might just mean it's not deployed globally yet. Some very basic testing proves they are cutting off requests pretty quickly. I'm wondering if they are detecting ytdl-core specifically somehow. Or maybe the user agent etc. I'll be getting some sleep then testing this pretty extensively I'll keep you updated to my findings

**Comment by Perflyst** [comment]
Google/YouTube has blocked my whole /64 IPv6 subnet due to one IPv6 address which I deployed recently to my [invidious](https://github.com/omarroth/invidious/) instance. The IPv4 address worked since a few months and is still working. Only IPv6 is blocked.

What provider do you use? I use Hetzner. Maybe it is something provider specific?

**Comment by odedhb** [comment]
It looks like just a new, more strict, throttling.
I’m trying exponential backoff.

**Comment by mh4ck** [comment]
I added some request caching (espacially for the video info) to my code - now 60% of servers are up again.

**Comment by Harmiox** [comment]
I'm still receiving this issue, and my program is barely even using any requests (maybe 50 In total today). At this point I'm not sure if these rate limits are any better than Youtube's own Data API v3.

**Comment by encloinc** [comment]
I fixed it by deploying different instances of the actual part of the code that downloads the youtube mp3's and having the main server pipe into one of these instances (at random). I made 15 of them, this seems its the only way to get past this atm.

**Comment by mh4ck** [comment]
> I fixed it by deploying different instances of the actual part of the code that downloads the youtube mp3's and having the main server pipe into one of these instances (at random). I made 15 of them, this seems its the only way to get past this atm.

You did it from 1 IP?

**Comment by mh4ck** [comment]
Anybody else had figured out smth. ? 

Interesting questions are:
How much requests could be done before they ban the IP?
How long will it take till the IP's are unblocked?

Haven't figured it out now.

**Comment by WaqasIbrahim** [comment]
@mh4ck I used 2 proxies (not rotating, static ip) last night for two different instances that were both blocked . But they seemed to work fine and did not get blocked even with high parallel traffic and still seem to be working.

**Comment by mh4ck** [comment]
> @mh4ck I used 2 proxies (not rotating, static ip) last night for two different instances that were both blocked . But they seemed to work fine and did not get blocked even with high parallel traffic and still seem to be working.

Where you got the proxies from? I bought today a lot of new ip's but all got blocked now.
Each IP had sent ~1 request in 10-30s...

**Comment by WaqasIbrahim** [comment]
@mh4ck It's a local service, so can't reveal that. But I have added more just to be safe and so far it has resolved the issue. What VPS service are you using? I tried adding another instacne and that was blocked instantly. Maybe it's targeting spefic vendors?

**Comment by omarroth** [comment]
See ytdl-org/youtube-dl#21729.

Similar to what @Perflyst mentioned I believe this is only an issue when connecting to YouTube over IPv6.

If possible, you may try disabling it or force connecting over IPv4. Unfortunately I'm not sure how easy that is only using this library, but it may be possible to disable it depending on cloud provider or some other configuration.

**Comment by mh4ck** [comment]
> See also [ytdl-org/youtube-dl#21729](https://github.com/ytdl-org/youtube-dl/issues/21729).
> 
> Similar to what @Perflyst mentioned I believe this is only an issue when connecting to YouTube over IPv6.
> 
> If possible, you may try disabling it or force connecting over IPv4. Unfortunately I'm not sure how easy that is only using this library, but it may be possible to disable it depending on cloud provider or some other configuration.

I'm only using IPv4 and still got this error after a few requests.

**Comment by ShivamJoker** [comment]
Guys guys guys please fix this issue as fast as possible. I have worked so hard on my music app from months if this thing happens my all work will be wasted @fent
Getting this today just requested few songs and error 429 coming
using AWS EC2 Mumbai

**Comment by mh4ck** [comment]
> Guys guys guys please fix this issue as fast as possible. I have worked so hard on my music app from months if this thing happens my all work will be wasted @fent
> Getting this today just requested few songs and error 429 coming
> using AWS EC2 Mumbai

I guess there is nothing programatically to do. 
YouTube just ban IP's that requests videos to fast.

**Comment by ShivamJoker** [comment]
@mh4ck so we are fucked up now. 😭

**Comment by fent** [comment]
whoever is getting this, can you log the url where it happens? not the video url but the urls passed to miniget [here](https://github.com/fent/node-miniget/blob/master/lib/index.js#L25). I'm curious if it's one of the urls used in `getInfo()` or if it's from the video download urls

**Comment by ShivamJoker** [comment]
@fent how to log it ???

**Comment by WaqasIbrahim** [comment]
@fent It's for the getInfo(), I use proxies for getInfo() and then I use those urls for further processing on VPS and they work fine.

**Comment by ShivamJoker** [comment]
@waqaslbrahim how do you use proxy can you please tell me also

**Comment by WaqasIbrahim** [comment]
@ShivamJoker Just pass an agent to requestOptions. I am using [https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent).

**Comment by encloinc** [comment]
> @waqaslbrahim how do you use proxy can you please tell me also

Dude relax itll be ok, I also have a site that Ive been working on a website for over a year that stopped working because of this. When this sort of stuff happens it is best you look for a short term solution by yourself while this gets fixed. What seemed to helpy me was deploying the part of my code that made a lot of youtube requests into different smaller deployments in what I think is the same ip, maybe thisll work for you.

**Comment by DELUUXE** [comment]
Any update on this?
Since i guess that using a proxy will get the proxy banned/rate limited pretty quick as well, and getting new IP's/proxies all the time isn't really a long term solution either.

**Comment by WaqasIbrahim** [comment]
@DELUUXE you can try rotating proxies, the IP changes on every request or you can set an interval.

**Comment by ShivamJoker** [comment]
Do you get proxy servers for free ?
Or you buy them from somewhere

**Comment by DELUUXE** [comment]
@WaqasIbrahim thanks for the suggestion, however as that option is quite expensive, i don't think that this is relevant to me either. 🤔 
Is this issue a thing that this library/package should fix (seeing the cause of the issue and resent bump in 924's) or rather something we (people who use ytdl) should fix (or rather work around) our self's?

**Comment by ShivamJoker** [comment]
guys there should be some way we can do this thing on client side (in browser generate link)
like youtube does and our problem solve 😆 
client's ip will ban if they request many songs at a time and most of us have dynamic ip at home
That's the solution

**Comment by DELUUXE** [comment]
@ShivamJoker keep in mind that not all "apps" have a front-end in the browser or aren't able to execute code on the client side.

**Comment by WaqasIbrahim** [comment]
@ShivamJoker Even if you have a front-end, you will not be able to make requests to YouTube due to CORS blocking them.

**Comment by ShivamJoker** [comment]
@WaqasIbrahim so how does the youtube fetches songs and videos ?? can't we implement something like that and put client's id instead of our server's

**Comment by edunad** [comment]
@ShivamJoker i've actually modified the lib to allow me doing that, tough you have to get the "get_info" json object on the client,then send that to the server for processing

**Comment by danielboos1** [comment]
i need a solution asap, i changed my ip about 11 times, what if we use windows? cause google tracks your cookies!

**Comment by ShivamJoker** [comment]
We all are waiting for solutions only 😒😒 you will have to change your sever for now

**Comment by danielboos1** [comment]
so wait if i use windows to host my bot , windows server will it work?

**Comment by ShivamJoker** [comment]
Just change your vps it should work make sure not to request many songs in less time

**Comment by danielboos1** [comment]
well the thing is, it is working on my current linux server but my bot is growing and too many people using the bot at the same time causing error 429. also how does this not happen to bigger bots?

**Comment by danielboos1** [comment]
lets all have a talk on discord, add me FighterMan0#0162. lets all create a group or a server and then we talk their for a solution.

**Comment by Harmiox** [comment]
Does anyone know if switching over to a NorthAmerican VPS would help with this issue? I currently use a German VPS.

**Comment by gomikestrat** [comment]
> @ShivamJoker Just pass an agent to requestOptions. I am using [https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent).

can you paste example code? thanks

**Comment by gomikestrat** [comment]
> Does anyone know if switching over to a NorthAmerican VPS would help with this issue? I currently use a German VPS.

i'm using a north american vps and i'm facing the same issue

**Comment by stephane-r** [comment]
Hello guys,

Same problem on **Hetzner** server. I'm not sure I understood the cause of the problem ? Is it fixed ?

**Comment by adamwoo2444** [comment]
same issue guys.Please fix this.

**Comment by fent** [comment]
for those experiencing this issue, try adding the option `range: { start: '0' }`. so like

```js
ytdl(videoUrl, { range: { start: '0' });
```

make sure it's `'0'`, the string, and not `0`, the number. let me know if this fixes your issue. if so, I can add it as a default option.

**Comment by adamwoo2444** [comment]
what this code will do? can you please tell?

**Comment by adamwoo2444** [comment]
@fent no, it did not.Its still the same issue.

**Comment by Harmiox** [comment]
> for those experiencing this issue, try adding the option `range: { start: '0' }`. so like
> 
> ```js
> ytdl(videoUrl, { range: { start: '0' });
> ```
> 
> make sure it's `'0'`, the string, and not `0`, the number. let me know if this fixes your issue. if so, I can add it as a default option.

This, very unfortunately, does not work.

**Comment by BlookyL** [comment]
This is happening to me to. It's pretty annoying for me and other people.
Anyone found a workaround yet?

**Comment by Harmiox** [comment]
I tried using another lib ([LavaLink](https://github.com/Frederikam/Lavalink)) but I still ran into the 429 issue.

**Comment by fent** [comment]
I don't know if youtube does, because I was never able to replicate it. but even if they don't, miniget will still retry the request.

**Comment by WaqasIbrahim** [comment]
@fent Thanks.

**Comment by Atruo** [comment]
@fent so basically if I change this file it will work? fent/node-miniget@1ed8467

**Comment by mahhov** [comment]
This still occurs, and retrying doens't help since all requests begin returning 429. I'm not sure this should be closed.
For my use case, I sent 1 request per 3-5 minutes, for about 7 hours (so about 140 requests total). 
I've sent 100 requests / hour for previously (months ago) and not had a similar issue.

**Comment by fent** [comment]
have you tried using cookies?



> edit, nevermind, I see this issue is still open here #635

I've kept that opened to remind myself to add throttling

**Comment by mahhov** [comment]
Yes, cookies worked, thanks.
I'm not sure throttling alone will avoid the issue since my use case was already a pretty slow rate of requests (1 per 3-5 minutes).

**Comment by mh4ck** [comment]
How long the cookies work, when they expire? Or they don't? Did anyone got experience with that?

**Comment by mahhov** [comment]
I would guess they would work for a few months; i.e. however long your youtube login remains valid.
Maybe there's a way to retrieve a new cookie with oauth?

**Comment by mh4ck** [comment]
I just tried cookies again but can't get it to work. Do you use the same IP for the cookie wich you used to create the cookie?

I generated it on my local pc and used it on my server - now i get the following error: 
**Error parsing info: Cookie header used in request, but unable to retrieve video metadata**

I'm pretty sure to use the right Cookie and identity-token... made xss attacks 10 years ago and normaly know what i'm doing haha...

```
let cookie = worker.getCookie();
        let idToken = worker.getIdentityToken();
        if(cookie && idToken) {
          console.log("[Info]: Using cookie for info request.");
          if(typeof opts.requestOptions.headers == "undefined") {
            opts.requestOptions.headers = {
              cookie: worker.getCookie(),
              'x-youtube-identity-token': worker.getIdentityToken()
            }
          } else {
            opts.requestOptions.headers.cookie = worker.getCookie();
            opts.requestOptions.headers['x-youtube-identity-token'] = worker.getIdentityToken();
          }
        }
```

**Comment by mahhov** [comment]
idk about your specific use case and what your `worker` is?
But for a simple example, just do:
```
ytdl(<id>, {
            ...
            requestOptions: {
                headers: {
                    'Cookie': '<paste cookie as string>'
                }
            }
        })
```
Where your cookie is a **string** (not an object) that includes `SID`, `HSID`, and `SSID`; e.g.
`'SID=<~70 characters>.;HSID=<~15 chars>; SSID=<~15 chars>;'` Note, unlike JSON, it's semicolon `;` deliminated and uses `=` instead of `:`.

**Comment by mahhov** [comment]
I've also gotten it to work with oauth, which imo is more versatile since it would be awkward to ask users to copy & paste cookies from their browser (unless there's an automated way of retrieving cookies I don't know about?)

```
ytdl(<id>, {
            ...
            requestOptions: {
                headers: {
                   Authorization: "Bearer ...",
                   Content-Type: "application/json"
                }
            }
        })
```

**Comment by fent** [comment]
what's all you need for oauth? i'd be interested in adding another example to the repo

**Comment by mahhov** [comment]
I use oauth for 2 things in my app. 1) (unrelated to ytdl, I use oauth to allow the user to add & remove videos to their playlists, and 2) to avoid the 429 error when downloading videos with ytdl in lieu of asking the user to copy paste a cookies from their browser.

**Comment by notadevps** [comment]
I am also getting same error any solutions?

**Comment by cchen028** [comment]
I'm getting 429 error as well. I hosted a function to get video info from Youtube using ytdl.GetBasicInfo, it seems like it happens every couple days, the last time it happened it made total of 9 requests before throwing the error. Though when I look at the log it seems like for every request it actually makes 2 request (one returning 204 preflight and one returning 200), not sure if this would be an issue? Anyone else facing similar issues?

**Comment by mahhov** [comment]
Did you guys (@notadevps & @cchen028) try using cookies or oauth token?

**Comment by notadevps** [comment]
yea i tried using cookies but it didn't worked

**Comment by mahhov** [comment]
Did your cookie look like: `'SID=<~70 characters>.;HSID=<~15 chars>; SSID=<~15 chars>;'`? Do you have a minimal reproducable example?

**Comment by fent** [comment]
if you got your cookies from `document.cookies`, try getting them from the header list in a request in the network tab. I've been told `document.cookie` omits some cookies

**Comment by cchen028** [comment]
Thanks for the prompt responses. Yes I have added the cookies and so far it is still working (Will give it a couple more days).
 
The reason I'm asking is because it works fine on my compute engine which runs 24/7 but not on the cloud functions. The 3 failures (err 429) I've encountered on cloud functions follow a similar pattern which is after the functions have been idled for a while and on the initial request it would fail until I re-deploy the function again. Just figured if anyone with a deeper understanding would know the potential cause behind this?

I'm also trying to keep the functions alive to see if this will solve it

**Comment by TehPigYT** [comment]
I'm getting the 429 status code too, sadly.
This is what I get in console
```js
Error: input stream: Status code: 429
at ClientRequest.<anonymous> (/home/container/node_modules/miniget/dist/index.js:150:31)
at Object.onceWrapper (events.js:417:26)
at ClientRequest.emit (events.js:310:20)
at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
at TLSSocket.socketOnData (_http_client.js:476:22)
at TLSSocket.emit (events.js:310:20)
at addChunk (_stream_readable.js:286:12)
at readableAddChunk (_stream_readable.js:268:9)
at TLSSocket.Readable.push (_stream_readable.js:209:10) ```

Are there any fixes for this?
