### ISSUE TITLE
Random ECONNRESET

### ISSUE THREAD

**Issue by MergHQ** [fent/node-ytdl-core#81]
Hello,

I've had a issue with this library ever since I started to use it. I basically pass the ytdl stream into ffmpeg to extract the audio from the video. Sometimes the stream crashes with an ECONNRESET, and i have no idea why.

Stacktrace:
`Error: read ECONNRESET 
    at exports._errnoException (util.js:1007:11) at TLSWrap.onread (net.js:563:26)`

**Comment by fent** [comment]
Do you have an example where this happens?

Is the example [here](https://github.com/fent/node-ytdl-core/blob/master/example/ffmpeg.js) similar?

**Comment by MergHQ** [comment]
@fent [This](https://github.com/MergHQ/DiscordMusicBot/blob/master/src/commands/songrequests/Player.js) is where it happens.

**Comment by MJunghenn** [comment]
Got that error, too. No specific Video or something just happened - and nothing can be downloaded.

**Comment by fent** [comment]
There's no need to call `ytdlStream.end()` btw, `.destroy()` should be enough in theory.

**Comment by hydrabolt** [comment]
Have been getting this error for a few months now...

**Comment by MergHQ** [comment]
I have noticed that using the audioonly flag actually helps. Doesn't throw that error so often anymore.

**Comment by fent** [comment]
Does this happen at the start of the download, middle, end?

**Comment by hydrabolt** [comment]
Mainly the end

**Comment by hydrabolt** [comment]
Towards the end

**Comment by ShahramJ** [comment]
Happening to me too.

**Comment by Brain-Gamer** [comment]
I have the same issue, but it happens to me in the middle / first half of the video

**Comment by derekmartinez18** [comment]
I've noticed the issue occur sporadically, sometimes I can go a few videos with nothing while others cut off half way or near the end of playback.

**Comment by Brain-Gamer** [comment]
Yeah I think it is pretty much random. But for me it's more often at the beginning of a video (most times)

**Comment by FireController1847** [comment]
Can also report this issue. Happens randomly through playback, just started happening recently. I've always had this with connection loss, but the bot is currently not losing connection and it's just happening while the song was playing fine. Seems to be more common in the past few days.

**Comment by FireController1847** [comment]
@fent People are saying it could be due to the fact you are downloading  videos "unofficially", or without a developer key.

**Comment by TinyMan** [comment]
Same over here, random but mostly after the middle of the video

**Comment by OzairP** [comment]
I'm still having issues with this in #128 even though the pull marked it as fixed.

**Comment by derekmartinez18** [comment]
I can also confirm that this issue is still occurring at roughly the same frequency.

**Comment by FireController1847** [comment]
I can confirm as well.

**Comment by Scott41** [comment]
Can confirm that this is still occurring about halfway through the stream.

**Comment by Ghoulean** [comment]
I almost always get this error at 1:23 when I try to stream this video: https://www.youtube.com/watch?v=iRSuh7OVdDs

This error occurs for me with every video longer than ~1min, but I found that that video throws the error fairly consistently.

**Comment by exception** [comment]
Can confirm, this is still occurring.

**Comment by Phineas** [comment]
Can also confirm.

**Comment by FireController1847** [comment]
Hey guys, he's actually currently working on a fix for it so we can stop confirming this, as the PR #128 should fix it.

**Comment by ibexes** [comment]
Related to this issue. Was getting the reset error, but I manually pulled the new commits (used the default npm installer previously). Reconnection seems to not work correctly, the video doesn't end correctly. Audio goes straight to the discord voice connector. Used this snippet of code (and modified) you provided on another thread `var ytdl = require('..');
var stream = ytdl('https://www.youtube.com/watch?v=6ySOK70gFPk');


var size;
stream.on('response', function(res) {
  size = res.headers['content-length'];
  console.log('size', size);
});

var dataEmitted = 0;
stream.on('data', function(chunk) {
  dataEmitted += chunk.length;
  console.log('on data', chunk.length, dataEmitted);
});

stream.on('end', function() {
  console.log('emitted', dataEmitted);
});`

This was the result. 
[log.txt](https://github.com/fent/node-ytdl-core/files/896541/log.txt)
The video that was causing it: https://www.youtube.com/watch?v=aatr_2MstrI

**Comment by TimeForANinja** [comment]
@ibexes did u try with the latest reg release(v11)?

**Comment by ibexes** [comment]
@TimeForANinja I believe so, yes. Previously it wouldn't even reconnect, it'd just throw the error. Now it just doesn't reconnect properly.

**Comment by TimeForANinja** [comment]
Try again with the master branch please
ran perfectly fine for me

**Comment by ibexes** [comment]
@TimeForANinja I do have a listener for errors, there apparently isn't an error and it just hangs at the last line of the log, instead of finishing and giving me an emitted. I'm filtering the stream for audio only if that makes a difference. 

I've isolated the code and it runs fine, in a single block. I'm using the stream with the playstream function in discord voice connection, so that could explain why there is an error, but I'm not sure why it hangs. It's only on a few random videos but they seem consistent and stop at the same location. I'm not sure how to recreate the environment in the isolated code since I don't know how the playstream function works exactly. I'll add a timestamp of the log and see the rate.
[log.txt](https://github.com/fent/node-ytdl-core/files/900058/log.txt)

The 'ended' at the end is printed when the discord playstream function has ended.

**Comment by Ghoulean** [comment]
> I'm filtering the stream for audio only if that makes a difference.

There is an 'audioonly' flag:

`stream = ytdl('https://www.youtube.com/watch?v=' + songId, {filter: 'audioonly'});`

**Comment by Ghoulean** [comment]
Works perfectly on my end. I get 'reason: Stream is not generating quickly enough.' when I reach the end of the video, so no more data can be streamed.

What reasons (if any) do the dispatcher and stream give when they end and/or they throw an error?

**Comment by ibexes** [comment]
Not sure if anyone's still working on this, since it was marked closed. I noticed that ```
// Install discord.js before running this!
const Discord = require('discord.js');
const ytdl    = require('..');

const client = new Discord.Client();
client.login('Mjk4MTA3NjMwMDA0NjAwODUz.C8UOQQ.Eg8kS01pRRq6dcZssHjBlSrE6Bg');

client.on('message', message => {
  if (message.content.startsWith('++play')) {
    const voiceChannel = message.member.voiceChannel;
    if (!voiceChannel) {
      return message.reply('Please be in a voice channel first!');
    }
    voiceChannel.join()
      .then(connnection => {
        let stream = ytdl('https://www.youtube.com/watch?v=aatr_2MstrI',{quality:249,filter : 'audioonly'});
		ytdl_debugger(stream,true);
        const dispatcher = connnection.playStream(stream);
        dispatcher.on('end', reason => {
			console.log("reason: "+reason);
          voiceChannel.leave();
        });
      });
  }
});

function ytdl_debugger(stream,debug){
	var size;
	stream.on('response', function(res) {
			  size = res.headers['content-length'];
			  if(debug) console.log('size', size);
			  });
	
	var dataEmitted = 0;
	stream.on('data', function(chunk) {
			  dataEmitted += chunk.length;
			  var date = new Date();
			  if(debug) console.log(date+': on data', chunk.length, dataEmitted);
			  });
	
	stream.on('end', function() {
			  if(debug) console.log('emitted', dataEmitted);
			  });
	stream.on('error', function(error) {
			  console.log(error);
			  });
	
}
```
I believe I've isolated it. It dies early if you're getting audio only and when it disconnects.

**Comment by fent** [comment]
From that log:
>size 1702823
>emitted 1670055

1702823 - 1670055 = 32768

Which is 16384 * 2. It reconnected twice, that must be related.

**Comment by fent** [comment]
Two things.

The inconsistent total emitted vs `content-length` is due to a bad `.unpipe()` that I just pushed.

The "Stream is not generating quickly enough." end message is from an error in discord.js, both with the latest [v11.0.0](https://github.com/hydrabolt/discord.js/blob/11.0.0/src/client/voice/pcm/FfmpegConverterEngine.js#L15) and with [latest](https://github.com/hydrabolt/prism-media/blob/master/src/transcoders/ffmpeg/FfmpegProcess.js#L62). If that `{ end: false }` is removed, the stream ends without issues. I'm not too familiar with discord.js, so I'm not sure why the transcoder stdin is kept open there.

There's also an [issue](https://github.com/hydrabolt/prism-media/issues/1) opened for that already

**Comment by godleydemon** [comment]
This seems to still be happening to me, where it's cutting the end of the song off.

**Comment by FireController1847** [comment]
@godleydemon Seems fine to me. I've only had some songs fail to load immideatly, but no songs cutting short.

**Comment by godleydemon** [comment]
@FireController1847 I'm willing to bet, what it does is times out how long it should be broadcasting, then sets that time by the video length. Then starts playing, but if there is any buffer time at all, that's how much the song will be cut off. It also might be the discord api I'm using that relies on ytdl as I just don't know enough to write my own.

**Comment by FireController1847** [comment]
@godleydemon What's the end reason? If the end reason is "The stream is not generating quickly enough", that means it is your internet, not the module.

**Comment by godleydemon** [comment]
@FireController1847 I just get playback finished and thats it. I don't get any other output in discord. I also don't get any output in console after the song ends. Unless this person didn't add any debug information into his api.

**Comment by FireController1847** [comment]
@godleydemon Discord.js has a Dispatcher.end event. You need to Console.log that event.

**Comment by godleydemon** [comment]
@FireController1847 I'm sorry, but this is a really stupid question, would you mind looking at my terrible api I'm utilizing here and telling me where I should put the debug for console.log? 
[https://hastebin.com/suyexoyija.php](url)

**Comment by FireController1847** [comment]
@godleydemon It cannot find the page, it gives me a 404.

**Comment by godleydemon** [comment]
@FireController1847 sorry about that, that's how bad this is getting I messed up the markup -.-

**Comment by FireController1847** [comment]
@godleydemon Add me on Discord. 
```
FireController1847#9085
```

**Comment by ibexes** [comment]
@godleydemon if you haven't resolved it yet, try git cloning the master branch and importing that instead, if you're currently using the npm install. I'm not entirely sure if it does it already but it's worth a try if you haven't done so already.

**Comment by fent** [comment]
The npm version is up  to date with the master branch. Or are you talking about discord.js?

Anyway, is the error you're getting ECONNRESET? Or something else?

Because you mentioned the stream ending right before it ends, it makes me suspect it's the "stream not generating quickly enough" end message that I addressed above.

**Comment by godleydemon** [comment]
@fent unfortunately, I still haven't solved it and if I just add in console log event for dispatcher.end it just says end in console. So either I'm not putting something in the right place, or something else. I ended up rewriting everything last night after everything was said and done. That wrapper api I was using was terrible and kept doing funky things.  I was able to figure out most of it lol
[New Code](https://hastebin.com/ruhuwiyiji.php)

So I'm doing it alot different from what I was before. It works and all, but I still get songs getting cut off from time to time.

**Comment by fent** [comment]
On line 37 of that you can add a `reason` argument to the `end` event from the dispatcher. Sometimes it'll end with a reason that can help knowing what happened.

**Comment by fent** [comment]
I just published a new version with a fix that I hope fixes this once and for all. It fixes the mysterious missing data and ending one buffer event earlier that @ibexes pointed out above, by properly cleaning up the previous request when reconnecting. 

A side effect of this error would be that it would mess up the audio decoder in discord.js, since it would skip part of the audio data, making it end the stream after a reconnect.

Please try it and let me know of this fixes this error on your end too.

**Comment by TesseractCat** [comment]
I think it might have fixed it for me, only time will tell though.

**Comment by TotomInc** [comment]
@fent I'm sorry to tell you that, but on the bot I'm currently working on it seems there is some missing data, especially at the end of a video. The bot is (not always, kinda random) missing the last few 5 ~ 10 seconds of a video.

The Discord stream ends with the reason `Stream is not generating quickly enough.` (which I highly doubt is from a bad connection, since the bot is hosted on a Compute Engine VM with 400mbps down/up).

If you want more info, you can take a [look at the repo](https://github.com/TotomInc/discord-stream).

**Comment by username99987** [comment]
Still happens. If I run locally, it works fine, but when I run it on a server, downloading stops 10-15 seconds before the video ends

**Comment by Spellminer** [comment]
Im also having the same issue as username99987, it runs fine on my computer, but running it on Google Cloud Platform, Amazon web services, SkySilk and Heroku all result in the audio cutting out before the song finishes.

**Comment by TotomInc** [comment]
@Spellminer this is currently discussed in #402
