### ISSUE TITLE
Error: imput stream: aborted

### ISSUE THREAD

**Issue by VoidDave** [fent/node-ytdl-core#902]
Today i wrote simple play command for discord bot.
But after some time of music plaing i get this error
My code for music play is:
`const { Permissions:{FLAGS} } = require ("discord.js")
const ytdl = require('ytdl-core')
const fs = require('fs')

module.exports={
    name: "play",
    description: "Puszczanie muzyki",
    args: true,
    usage: "<tytuł/url>",
    guildOnly: true,
    cooldown: 10,
    aliases: ["p"],
    botPermissions: [FLAGS.CONNECT,FLAGS.SPEAK],

    async run(message, args) {

        //console.log(args)
        const voiceChannel = message.member.voice.channel
      if(!voiceChannel) return message.channel.send("Potrzebujesz być na kanale głosowym by to zrobić")
      
      try {
          var connection = await voiceChannel.join()
          } catch (error) {
              console.log(`There was an error connecting to the voice channel: ${error}`)
          }
          
          const dispatcher = connection.play(ytdl(args[0],{Quality: 'highestaudio'},{filter:'audiooly'},{highWaterMark: 1<<23},{dlChunkSize:0}))
          .on('finish',() => {
             voiceChannel.leave()
          })
          .on('error', error => {
             console.log(error)
          })
          dispatcher.setVolumeLogarithmic(5 / 5)
    }
}
`
Any ideas how to fix it ?
![print screen](https://user-images.githubusercontent.com/62336875/111180167-0be00800-85ad-11eb-8b8e-aec97c9181be.png)

**Comment by fent** [comment]
does calling ytdl by itself show this error too? or only with discordjs? what's your version? a similar bug was recently fixed.

**Comment by VoidDave** [comment]
I dont know .
And im using the newest version of discord js and ytdl
How similar bug was fixed ?

**Comment by super1zero** [comment]
Question: how can i get the transcript from the youtube url?

**Comment by Sheff93** [comment]
I have this error show up quite frequently.
I've run the ytdl-core tests by cloning the repo etc and no issues there
The issue seems to arise after some time of playing, at which point it will crash and throw the error mentioned earlier.

I am running discord js 12.5.1 and ytdl-core 4.5.0
This has been occurring across multiple versions of ytdl-core for me.

**Comment by LordFarquhar** [comment]
I am having this issue as well
I can play about 3 or 4 songs and then this issue occurs>
Interestingly it is not at the beginning or end of a video but can be anywhere randomly

I too am using Discord.js and this error is called from the Discord Voice Dispatcher however it is clearly in relation to the input stream, which in our case is ytdl-core

Raspberry Pi (Raspbian - latest)
ytdl-core @4.5.0
ffmpeg-static @4.2.8
discord.js @12.5.1
@discord.js/opus @0.3.3

**Comment by VoidDave** [comment]
Today i runed test that author submit in the his code and got this error : (logs below)
`0 verbose cli [
0 verbose cli   'D:\\nodejs\\node.exe',
0 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'run',
0 verbose cli   'test:irl'
0 verbose cli ]
1 info using npm@7.5.1
2 info using node@v15.8.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:D:\nodejs\node_modules\npm\npmrc Completed in 3ms
5 timing config:load:builtin Completed in 3ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:C:\Users\polsk\Downloads\node-ytdl-core-master\node-ytdl-core-master\.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\polsk\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Users\polsk\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 7ms
19 verbose npm-session 588df15ba9a49949
20 timing npm:load Completed in 14ms
21 timing command:run-script Completed in 7681ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (D:\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:378:20)
22 verbose stack     at maybeClose (node:internal/child_process:1067:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
23 verbose pkgid ytdl-core@0.0.0-development
24 verbose cwd C:\Users\polsk\Downloads\node-ytdl-core-master\node-ytdl-core-master
25 verbose Windows_NT 10.0.19042
26 verbose argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:irl"
27 verbose node v15.8.0
28 verbose npm  v7.5.1
29 error code 4
30 error path C:\Users\polsk\Downloads\node-ytdl-core-master\node-ytdl-core-master
31 error command failed
32 error command C:\Windows\system32\cmd.exe /d /s /c mocha --timeout 16000 test/irl-test.js
33 verbose exit 4
`

**Comment by flojo007** [comment]
Hi,

I'm getting this error too
![grafik](https://user-images.githubusercontent.com/83416975/118407925-459fbe80-b683-11eb-8d35-ee2662af8da1.png)

ytdl-core@4.8.0
ffmpeg-static@4.3.0
discord.js@12.5.3
@discord.js/opus@0.3.3
I can provide more info if needed

**Comment by TimeForANinja** [comment]
🤔 it would be cool to do some modifications to discord.js to check for ffmpeg errors

other than that this is pretty unfixable in the current situation... 
we'd need a way to reproduce this error without discord.js... or at least narrow down if it is actually discord.js or ytdl-core...

**Comment by LordFarquhar** [comment]
So im running a small discord bot called Tinker
I run development on my laptop and production on my raspberry pi. The issue does not seem to occur when in development. The only differences are, of course the OS, and the nodejs version. The code is the *exact* same
Here are the stats of the two:

**Development** (no issues)
Windows Home (latest updates)
`node index.js` run directly in terminal (Command Prompt)
nodejs: v14.16.1

**Production** (fairly regular "Input Stream Aborted" errors)
Raspbian (latest updates)
`pm2 start tinker` pm2 process manager, configured with the correct nodejs runtime
nodejs: v16.0.0

**Comment by Topiya** [comment]
> So im running a small discord bot called Tinker
> I run development on my laptop and production on my raspberry pi. The issue does not seem to occur when in development. The only differences are, of course the OS, and the nodejs version. The code is the _exact_ same
> Here are the stats of the two:
> 
> **Development** (no issues)
> Windows Home (latest updates)
> `node index.js` run directly in terminal (Command Prompt)
> nodejs: v14.16.1
> 
> **Production** (fairly regular "Input Stream Aborted" errors)
> Raspbian (latest updates)
> `pm2 start tinker` pm2 process manager, configured with the correct nodejs runtime
> nodejs: v16.0.0
> 
> _Edit_
> 
> I have just done a further test, running my production with all the same settings and system but with nodejs v 14.16.1 and no errors whatsoever. Nodejs version appears to be the culprit (at least in my instance). I hope this helps some people with issues and the devs with fixing the error. Love the package and keep up the good work!

@LordFarquhar Did you find any solution yet ? I am facing a same issue.

**Comment by LordFarquhar** [comment]
Changing that node version seemed to solve it all for me

**Comment by Topiya** [comment]
> Changing that node version seemed to solve it all for me

@LordFarquhar Thank you for the reply. Can you let me know which version of node and pm2 did you use in production?

**Comment by Hazmi35** [comment]
Can reproduce on Windows and Linux on Node.js v16 (16.5.0), but this issue does not exist on v14 (14.17.3). Using ytdl-core and piping it to fs.createWriteStream does not have any issue, only if ytdl-core + Discord.js has this issue, probably related to discordjs/discord.js#5214, and probably has something to do with highWatermark, will update the situation later

**Comment by LordFarquhar** [comment]
Node LTS, pm2 latest update
DiscordJS is at the latest stable update

**Comment by Hazmi35** [comment]
> Can reproduce on Windows and Linux on Node.js v16 (16.5.0), but this issue does not exist on v14 (14.17.3). Using ytdl-core and piping it to fs.createWriteStream does not have any issue, only if ytdl-core + Discord.js has this issue, probably related to [discordjs/discord.js#5214](https://github.com/discordjs/discord.js/issues/5214), and probably has something to do with highWatermark, will update the situation later

Setting highWatermark option to 32MiB on Node.js v16 (16.5.0) fixes the problem

**Comment by rojserbest** [comment]
I've the same problem. I'm streaming to Telegram.

**Comment by rojserbest** [comment]
![image](https://user-images.githubusercontent.com/49933115/127537175-e684d695-09af-491e-88de-97e02895e977.png)
Here are my options.

**Comment by rojserbest** [comment]
![image](https://user-images.githubusercontent.com/49933115/127537445-118eb513-7a17-4ad1-95e8-0e1c0559971e.png)
Oh and here's my Node version.

**Comment by rojserbest** [comment]
> thinking it would be cool to do some modifications to discord.js to check for ffmpeg errors
> 
> other than that this is pretty unfixable in the current situation...
> we'd need a way to reproduce this error without discord.js... or at least narrow down if it is actually discord.js or ytdl-core...

Here I get it without Discord.js, @TimeForANinja. :)

I'm using [ytdl-core-telegram](https://github.com/rojserbest/ytdl-core-telegram), [gram-tgcalls](https://github.com/tgcallsjs/gram-tgcalls) and [GramJS](https://github.com/gram-js/gramjs).

**Comment by rojserbest** [comment]
Here's my full source code: https://github.com/callsmusic/callsmusicremix

**Comment by redbrain** [comment]
@GaryCraft Try using a stable version of Node (ie the v14 LTS) and see if that fixes it?

**Comment by GaryCraft** [comment]
@redbrain the thing is that I need to use Node v 16+

**Comment by ARR4NN** [comment]
I am having the same issue with it aborting playing.
![image](https://user-images.githubusercontent.com/70060472/129752708-df8dd56a-32d9-40ac-8441-0afd7d27f2fa.png)

![image](https://user-images.githubusercontent.com/70060472/129752657-78551d53-f897-4565-b9c1-936c2d1e5d62.png)

**Comment by mtripg6666tdr** [comment]
I am having tha same issue.
I got a direct video url (like `https://r8--***.googlevideo.com/videoplayback?***`) via [`youtube-dl`](https://github.com/ytdl-org/youtube-dl) and tried playing directly with [`miniget`](https://github.com/fent/miniget) and the url, but aborted error was still occurred.
Though this is not what prove the issue is of miniget, I think it might be the helpful information.
![image](https://user-images.githubusercontent.com/56076195/130165684-b36f89ed-8deb-43ee-8db2-31be84c0aee9.png)
`highWaterMark` option won't solve the actual cause of the issue because it only makes the time to occurred an error longer.

**Comment by mtripg6666tdr** [comment]
I can reproduce the issue only with `node`(v16.6.1), `ytdl-core`(v4.9.1), `prism-media`(v1.3.2) and `node-opus`(v0.3.3).
I don't know if this is helpful but the complete source code is here: https://github.com/mtripg6666tdr/ytdl-test/blob/master/src/index.js

**Comment by Gary50613** [comment]
I've noticed that this error happens every time when a song plays to 30 minutes

**Comment by mtripg6666tdr** [comment]
Maybe the time when this error occur related to `highWaterMark` and actual size of the stream.
When I played a stream, it occurred in sometimes 44 minutes, at other times in 28 minutes (`highWaterMark` was set default).
When I played an other stream, it occurred in 57 seconds.

**Comment by Gary50613** [comment]
is this looks like the same problem fent/node-feedsub#60

**Comment by mtripg6666tdr** [comment]
> is this looks like the same problem [fent/node-feedsub#60](https://github.com/fent/node-feedsub/issues/60)

This error occurs nodejs v15 or more only, same as the issue you mentioned.
So this issue might be solved by updating miniget version. (unverified yet)
I will try it!

**Comment by Gary50613** [comment]
> > is this looks like the same problem [fent/node-feedsub#60](https://github.com/fent/node-feedsub/issues/60)
> 
> This error occurs nodejs v15 or more only, same as the issue you mentioned.
> So this issue might be solved by updating miniget version. (unverified yet)
> I will try it!

i just tried to fork this repo and update miniget to v4.2.1 and still gets the problem

**Comment by mtripg6666tdr** [comment]
Unfortunately I also got the problems with `miniget@4.2.0` just same as you in 14 minutes.

**Comment by mtripg6666tdr** [comment]
I captured network traffic using Wireshark.
I found that a remote server sends a "TCP [RST]" packet (to close the connection) after the node.js sends "TCP ZeroWindow" packets some times. Also I've noticed a "TCP Window Update" packet is successfully sent some times.
However I couldn't found any invalid network packet likely to cause connection reset. It looks like all working properly. (I might have overlooked because I'm a newbie of analyzing of network)
![image](https://user-images.githubusercontent.com/56076195/130314497-b2ca27a8-1b07-42c3-b4e8-7d9ba0f2fd2d.png)

Anyway, if you want to use discord.js v13, I noticed you can provisionally use discord.js v13 with Node.js v14 or less.
In order to run discord.js v13 on Node.js v14 or less, (a tricky way though) install `AbortController` npm package and write code below before calling the discord.js module. This makes discord.js work properly.
```javascript
global.AbortController = require("AbortController");
```
Of course this solution might become unusable depending on updates since this is not a solution to the actual cause and right way to use discord.js v13.
This works currently properly in my environment.
sorry for my bad english

**Comment by rojserbest** [comment]
cmon speak for telegram too, telegram is a thing too hehe

**Comment by mtripg6666tdr** [comment]
> cmon speak for telegram too, telegram is a thing too hehe

Does telegram bots need Node.js v15 or later?

**Comment by rojserbest** [comment]
> > cmon speak for telegram too, telegram is a thing too hehe
> 
> Does telegram bots need Node.js v15 or later?

Depends on what lib you use, normal Telegram bots can’t speak in voice chats. You should use a userbot with an MTProto lib to join a call and a Telegram WebRTC library to stream.

I’m using [GramJS](http://github.com/gram-js/gramjs] as the MTProto library, [GramTGCalls](http://github.com/tgcallsjs/gram-tgcalls) and [grammY](http://github.com/grammyjs/grammy) for the bot.

My source code is [here](http://github.com/callsmusic/remix).

**Comment by mtripg6666tdr** [comment]
> > > cmon speak for telegram too, telegram is a thing too hehe
> > 
> > 
> > Does telegram bots need Node.js v15 or later?
> 
> Depends on what lib you use, normal Telegram bots can’t speak in voice chats. You should use a userbot with an MTProto lib to join a call and a Telegram WebRTC library to stream.
> 
> I’m using [GramJS](https://github.com/gram-js/gramjs) as the MTProto library, [GramTGCalls](https://github.com/tgcallsjs/gram-tgcalls) and [grammY](https://github.com/grammyjs/grammy) for the bot.
> 
> My source code is [here](https://github.com/callsmusic/remix).

I cloned it and tried removing `engines` lines in `package.json` and executing `npm install --engine-strict` but no error displayed
![image](https://user-images.githubusercontent.com/56076195/130317772-067b502c-bff3-479d-a964-7e87093d742f.png)
So if the source code of the bot doesn't contain any code that can be work only with Node.js v15 or later, the bot might work in Node.js v14 or less.
Could you try to run `npm i node@v14-lts` and execute `npx node dist`

My node.js and npm versions are:
Node: `v14.16.0`
npm: `7.21.0`

**Comment by rojserbest** [comment]
> > > > cmon speak for telegram too, telegram is a thing too hehe
> > > 
> > > 
> > > Does telegram bots need Node.js v15 or later?
> > 
> > 
> > Depends on what lib you use, normal Telegram bots can’t speak in voice chats. You should use a userbot with an MTProto lib to join a call and a Telegram WebRTC library to stream.
> > I’m using [GramJS](https://github.com/gram-js/gramjs) as the MTProto library, [GramTGCalls](https://github.com/tgcallsjs/gram-tgcalls) and [grammY](https://github.com/grammyjs/grammy) for the bot.
> > My source code is [here](https://github.com/callsmusic/remix).
> 
> I cloned it and tried removing `engines` lines in `package.json` and executing `npm install --engine-strict` but no error displayed
> ![image](https://user-images.githubusercontent.com/56076195/130317772-067b502c-bff3-479d-a964-7e87093d742f.png)
> So if the source code of the bot doesn't contain any code that can be work only with Node.js v15 or later, the bot might work in Node.js v14 or less.
> Could you try to run `npm i node@v14-lts` and execute `npx node dist`
> 
> My node.js and npm versions are:
> Node: `v14.16.0`
> npm: `7.21.0`

Did you try playing a live YouTube video?

**Comment by rojserbest** [comment]
> > > > cmon speak for telegram too, telegram is a thing too hehe
> > > 
> > > 
> > > Does telegram bots need Node.js v15 or later?
> > 
> > 
> > Depends on what lib you use, normal Telegram bots can’t speak in voice chats. You should use a userbot with an MTProto lib to join a call and a Telegram WebRTC library to stream.
> > I’m using [GramJS](https://github.com/gram-js/gramjs) as the MTProto library, [GramTGCalls](https://github.com/tgcallsjs/gram-tgcalls) and [grammY](https://github.com/grammyjs/grammy) for the bot.
> > My source code is [here](https://github.com/callsmusic/remix).
> 
> I cloned it and tried removing `engines` lines in `package.json` and executing `npm install --engine-strict` but no error displayed
> ![image](https://user-images.githubusercontent.com/56076195/130317772-067b502c-bff3-479d-a964-7e87093d742f.png)
> So if the source code of the bot doesn't contain any code that can be work only with Node.js v15 or later, the bot might work in Node.js v14 or less.
> Could you try to run `npm i node@v14-lts` and execute `npx node dist`
> 
> My node.js and npm versions are:
> Node: `v14.16.0`
> npm: `7.21.0`

Did you try playing a live YouTube video?

**Comment by mtripg6666tdr** [comment]
I'm sorry I don't have any telegram account so I didn't test it.

**Comment by rojserbest** [comment]
> I'm sorry I don't have any telegram account so I didn't test it.

OK lol.

**Comment by mtripg6666tdr** [comment]
So I wrote
> Could you try to run `npm i node@v14-lts` and execute `npx node dist`

**Comment by x5engine** [comment]
> > I'm sorry I don't have any telegram account so I didn't test it.
> 
> OK lol.

I love this solution :D

**Comment by roj1512** [comment]
Sad.

**Comment by mtripg6666tdr** [comment]
Recently I came up with idea with fragmental downloads.
and everything works well for me by downloading tiny fragments that are each as small as 1MB and piping them into one stream.
for example:
```ts
export function createYTStream(info:ytdl.videoInfo, format:ytdl.videoFormat, options:ytdl.downloadOptions, chunkSize:number = 512 * 1024 /*stream size of each partial stream*/){
  const stream = new PassThrough();
  let current = -1;
  const contentLength = Number(format.contentLength);
  if(contentLength < chunkSize){
    // stream is tiny so unnecessary to split
    ytdl.downloadFromInfo(info, {format, ...options}).pipe(stream);
  }else{
    // stream is big so necessary to split
    const pipeNextStream = () => {
      current++;
      let end = chunkSize * (current + 1) - 1;
      if(end >= contentLength) end = undefined;
      const nextStream = ytdl.downloadFromInfo(info, {format, ...options, range: {
        start: chunkSize * current, end
      }});
      nextStream.pipe(stream, {end: end === undefined});
      if(end !== undefined){
        // schedule to pipe next partial stream
        nextStream.on("end", () => {
          pipeNextStream();
        });
      }
    };
    pipeNextStream();
  }
  return stream;
}
```
I hope this will help.
P.S. the tricky solution that I wrote in this issue doesn't work well now in current version of discord.js. It will work in discord.js v13.1.0 **only**.

**Comment by ppodds** [comment]
Still broken.

A substitute package: https://www.npmjs.com/package/play-dl

**Comment by luisAzcuaga** [comment]
> > Can reproduce on Windows and Linux on Node.js v16 (16.5.0), but this issue does not exist on v14 (14.17.3). Using ytdl-core and piping it to fs.createWriteStream does not have any issue, only if ytdl-core + Discord.js has this issue, probably related to [discordjs/discord.js#5214](https://github.com/discordjs/discord.js/issues/5214), and probably has something to do with highWatermark, will update the situation later
> 
> Confirmed, setting ytdl-core highWatermark option to 32MiB on Node.js v16 (16.5.0) fixes the problem, so the workarounds are use Node v14.x or play with the highWatermark settings, not sure if this will apply to everyone

Thanks a lot!
I did that `highWaterMark` solution and fixed at least for an almost 4 minutes long song ("Something About Us"), also tested with "All Nightmare Long" and "The Day that Never Comes" (both ~8 mins)

![image](https://user-images.githubusercontent.com/37643667/158101058-6186304e-5b82-48b7-975d-c312ed1df671.png)

I'm currently using 
`Node v16.14.0`
And here are my other module versions :)
```json
    "@discordjs/opus": "^0.7.0",
    "discord.js": "^12",
    "dotenv": "^16.0.0",
    "ffmpeg": "^0.0.4",
    "ffmpeg-static": "^4.4.1",
    "fluent-ffmpeg": "^2.1.2",
    "ytdl-core": "^4.11.0"
```

**Comment by mtripg6666tdr** [comment]
I heard `play-dl` won't cause the issue.
At least at the current you can let `highWaterMark` much higher, use my above *fragmental download* approach, downgrade Node.js to v15 or lower, or `play-dl` to prevent from the issue.

**Comment by maximosdrr** [comment]
Is there any solution yet ?

**Comment by maximosdrr** [comment]
> Still broken.
> 
> A substitute package: https://www.npmjs.com/package/play-dl

This solve my problem, unfortunately ytdl still broken given an issue with miniget

**Comment by Tomato6966** [comment]
```js
const ytdl = require("ytdl-core");

const stream = ytdl("song-url", {
     filter: "audioonly",
     fmt: "mp3",
     highWaterMark: 1 << 62,
     bitrate: 128,
     liveBuffer: 1 << 62,
     quality: "lowestaudio",
});
```
Using such settings from ytdl-core allows you playing songs over 60 mins with easy and no abortion error at all
> 1 << 62 gives the biggest number

Why bitrate 128?
> Discord can not transfer audio with an higher bitrate! (unless 3 boost levels and bitrate is at 396kbps)
> Valid bitrates: 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256 and 320 kBit/s
> Why quality lowestaudio, you won't hear that much of a difference?

**Comment by ddoodm** [comment]
Thanks heaps @Tomato6966 - can confirm that fixed it for me with a 3 hour stream

**Comment by eugabrielsilva** [comment]
@varun-s22 even with this settings, the problem still occurs :(
hopely waiting for a fix from @fent

**Comment by varun-s22** [comment]
> @varun-s22 even with this settings, the problem still occurs :( hopely waiting for a fix from @fent

hey @eugabrielsilva, it works fine for like a hour or something.. so its kind of a temporary solution, so :)

**Comment by 0xAnakin** [comment]
I use this plugin to broadcast the audio to an ice-cast server. This is what worked for me (no more aborted error).

```js
this.yt_download = yt_download(song.data.url, {
    filter: 'audioonly',
    fmt: 'mp3',
    highWaterMark: 1 << 30,
    liveBuffer: 20000,
    dlChunkSize: 4096,
    bitrate: 128,
    quality: 'lowestaudio'
}).once('error', (err) => {

    console.error(`[${this.name}]:`, err.message, '\n', err.stack);

    if (err.message.includes('410')) {
        this.removeItem(song);
    }

    this.next();

}).once('end', () => {

    console.log(`[${this.name}]: Downloaded song ${song.data.title}`);

}).pipe(this.ffmpeg.stdin);
```

**Comment by eugabrielsilva** [comment]
> > @varun-s22 even with this settings, the problem still occurs :( hopely waiting for a fix from @fent
> 
> hey @eugabrielsilva, it works fine for like a hour or something.. so its kind of a temporary solution, so :)

Weird thing is that, in my case, it still plays for about 15 seconds and then the stream aborts...

**Comment by eugabrielsilva** [comment]
@0xAnakin where is the "this.ffmpeg.stdin" coming from? How can I implement this?

**Comment by 0xAnakin** [comment]
> @0xAnakin where is the "this.ffmpeg.stdin" coming from? How can I implement this?

This has nothing to do with the fix. the "fix" in my case were the options object passed this one:

```
{
    filter: 'audioonly',
    fmt: 'mp3',
    highWaterMark: 1 << 30,
    liveBuffer: 20000,
    dlChunkSize: 4096,
    bitrate: 128,
    quality: 'lowestaudio'
}
```

In my case I wanted to pass the download to ffmpeg for further processing, This is not something you should worry about. I just copied the code from my script. just try the settings I pasted above. Also as a side note I should mention that I didnt get any "Aborted" errors when i was running my app locally, the issues started once I uploaded it on VPS server. After lots of trial and error and testing these settings worked for me. Hope it helps...

**Comment by BlackusPL** [comment]
> > @0xAnakin where is the "this.ffmpeg.stdin" coming from? How can I implement this?
> 
> @eugabrielsilva this has nothing to do with the fix. The "fix" in my case were the options object passed. This one:
> 
> ```js
> {
>     filter: 'audioonly',
>     fmt: 'mp3',
>     highWaterMark: 1 << 30,
>     liveBuffer: 20000,
>     dlChunkSize: 4096,
>     bitrate: 128,
>     quality: 'lowestaudio'
> }
> ```
> 
> In my case I wanted to pass the download to ffmpeg for further processing, This is not something you should worry about. I just copied the code from my script. just try the settings I pasted above. Also as a side note I should mention that I didnt get any "Aborted" errors when i was running my app locally, the issues started once I uploaded it on VPS server. After lots of trial and error and testing these settings worked for me. Hope it helps...

For me everything works fine for 1 minute. After song stops, no console error and no Aborted. Any solution?

**Comment by Denveous** [comment]
Still no valid solutions? 2024 and still this issue persists in discord/js bots.

**Comment by eugabrielsilva** [comment]
> Still no valid solutions? 2024 and still this issue persists in discord/js bots. The one provided above by 0xAnakin doesn't work.

I just gave up of this package. Switched over [@distubejs/ytdl-core](https://github.com/distubejs/ytdl-core). Working perfectly for this situation.

**Comment by Denveous** [comment]
> > Still no valid solutions? 2024 and still this issue persists in discord/js bots. The one provided above by 0xAnakin doesn't work.
> 
> I just gave up of this package. Switched over [@distubejs/ytdl-core](https://github.com/distubejs/ytdl-core). Working perfectly for this situation.

Well if I could hug you I would, besides the fact just reinstalling discord/js didn't work, I hate to force it to update to the latest version (npm i @discordjs/voice@latest) and switched to the core you use and I'm in business again. Appreciate the quick response!

**Comment by Denveous** [comment]
> > Still no valid solutions? 2024 and still this issue persists in discord/js bots. The one provided above by 0xAnakin doesn't work.
> 
> I just gave up of this package. Switched over [@distubejs/ytdl-core](https://github.com/distubejs/ytdl-core). Working perfectly for this situation.

Well if I could hug you I would, I hate to force it to update to the latest version of discord/js (npm i @discordjs/voice@latest) and switched to the core you use and I'm in business again. Appreciate the quick response!

**Comment by Denveous** [comment]
> > Still no valid solutions? 2024 and still this issue persists in discord/js bots. The one provided above by 0xAnakin doesn't work.
> 
> I just gave up of this package. Switched over [@distubejs/ytdl-core](https://github.com/distubejs/ytdl-core). Working perfectly for this situation.

Well if I could hug you I would, I hate to force it to update to the latest version of discord/js (**npm i @discordjs/voice@latest**) and switched to the core you use and I'm in business again. Appreciate the quick response!

**Comment by Denveous** [comment]
> > Still no valid solutions? 2024 and still this issue persists in discord/js bots. The one provided above by 0xAnakin doesn't work.
> 
> I just gave up of this package. Switched over [@distubejs/ytdl-core](https://github.com/distubejs/ytdl-core). Working perfectly for this situation.

Well if I could hug you I would, I had to force it to update to the latest version of discord/js (npm i @discordjs/voice@latest) and switched to the core you use and I'm in business again. Appreciate the quick response!

**Comment by ELJoOker2004** [comment]
> > ```js
> > const ytdl = require("ytdl-core");
> > 
> > const stream = ytdl("song-url", {
> >      filter: "audioonly",
> >      fmt: "mp3",
> >      highWaterMark: 1 << 62,
> >      liveBuffer: 1 << 62,
> >      dlChunkSize: 0, //disabling chunking is recommended in discord bot
> >      bitrate: 128,
> >      quality: "lowestaudio",
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Using such settings from ytdl-core allows you playing songs over 60 mins with easy and no abortion error at all
> > > 1 << 62 gives the biggest number
> > 
> > 
> > Why bitrate 128?
> > > Discord can not transfer audio with an higher bitrate! (unless 3 boost levels and bitrate is at 396kbps)
> > > Valid bitrates: 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256 and 320 kBit/s
> > > Why quality lowestaudio, you won't hear that much of a difference?
> 
> Thanks it surely helped.. although can you explain what are highWaterMark and liveBuffer options

I want to know too what are highWaterMark and liveBuffer options, and when should I increase or decrease them

**Comment by Tomato6966** [comment]
highWaterMark is a limit (threshhold), which limits the amount of data which is cacheable by the internal (audio playback) stream.
E.g. you could buffer 1s, or 60 s.
On default it's 1 << 4, which equals to 16 and this means it stores 16 items in a buffer, before re-fetching the data to play again.
If you set it to 1 << 64 is the maximum of data, like all get's buffered. because it either way fetches everything
It makes loading maybe 1ms longer but it buffers the data and thus is less likely to fail.

Same for liveBuffer but that's just for live stream

*note: the exact amount of buffering, is not really declareable due to nodejs*

**Comment by ELJoOker2004** [comment]
> highWaterMark is a limit (threshhold), which limits the amount of data which is cacheable by the internal (audio playback) stream. E.g. you could buffer 1s, or 60 s. On default it's 1 << 4, which equals to 16 and this means it stores 16 items in a buffer, before re-fetching the data to play again. If you set it to 1 << 64 is the maximum of data (1073741824 items ), like for normal videos we aim to buffer everything, to reduce likely issues because it either way fetches everything. If it's a 10hr video, it buffers like 2/10ths of it per internal fetch It makes loading maybe 1ms longer but it buffers the data and thus is less likely to fail.
> 
> Same for liveBuffer but that's just for live stream
> 
> _note: the exact amount of buffering, is not really declareable due to nodejs_

tysm for response, I got it now <3
